version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: chatSchema
      MYSQL_USER: amr
      MYSQL_PASSWORD: password123
    ports:
       - "3307:3306"

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build: .
    command: bash -c "bash ./init.sh"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - chatworker
      - messageworker
    ports:
      - '3000:3000'
    environment:
      DB_NAME: chatSchema
      DB_USER: amr
      DB_PASSWORD: password123
      DB_HOST: db
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq

  chatworker:
    build: .
    command: rake sneakers:run
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_NAME: chatSchema
      DB_USER: amr
      DB_PASSWORD: password123
      DB_HOST: db
      RABBITMQ_HOST: rabbitmq
      WORKERS: ChatWorker

  messageworker:
    build: .
    command: rake sneakers:run
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_NAME: chatSchema
      DB_USER: amr
      DB_PASSWORD: password123
      DB_HOST: db
      RABBITMQ_HOST: rabbitmq
      WORKERS: MessageWorker
